// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLKZK2aiaZk8U9Hp0yVuyTZJ9yIVduZs',
    appId: '1:119118805198:web:5a8032345d18c0d325389f',
    messagingSenderId: '119118805198',
    projectId: 'legalai-eba3b',
    authDomain: 'legalai-eba3b.firebaseapp.com',
    storageBucket: 'legalai-eba3b.firebasestorage.app',
    measurementId: 'G-C933D618XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_LxTOEZdNn-HenVBcq8NL-1gFlmD5n_M',
    appId: '1:119118805198:android:fb90453c6d10858b25389f',
    messagingSenderId: '119118805198',
    projectId: 'legalai-eba3b',
    storageBucket: 'legalai-eba3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbmwAzud4JyfDTQCftQmQgUaxY5D_Q04',
    appId: '1:119118805198:ios:3db637f3666082af25389f',
    messagingSenderId: '119118805198',
    projectId: 'legalai-eba3b',
    storageBucket: 'legalai-eba3b.firebasestorage.app',
    iosBundleId: 'kz.legalhelp.app',
  );
}
